// app/layout.tsx

import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import ClientOnlyLayout from "@/components/clientLayout"
import { TRPCProvider } from "@/components/trpc-provider";
import { ThemeProvider } from "@/components/theme-provider"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}><ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <Providers>
          <ClientOnlyLayout>
            <TRPCProvider>
              {children}
            </TRPCProvider>
          </ClientOnlyLayout>
        </Providers>
      </ThemeProvider>

      </body>
    </html>
  );
}
